// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuyD5evbkbnqQbvcqXg124aXYucFOwPOw',
    appId: '1:429164703926:web:4a7c02b9b20e9c6cfbb617',
    messagingSenderId: '429164703926',
    projectId: 'esec-bus-01',
    authDomain: 'esec-bus-01.firebaseapp.com',
    storageBucket: 'esec-bus-01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmr0gPuFI3JaHO0GsCC6fKsmy8cn9-Kkw',
    appId: '1:429164703926:android:c19c5e7543da5b7dfbb617',
    messagingSenderId: '429164703926',
    projectId: 'esec-bus-01',
    storageBucket: 'esec-bus-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM_gcg5kI4V40oJK_1TxpC5H_UFfLNB4I',
    appId: '1:429164703926:ios:96d7952d75e3cee8fbb617',
    messagingSenderId: '429164703926',
    projectId: 'esec-bus-01',
    storageBucket: 'esec-bus-01.firebasestorage.app',
    iosBundleId: 'com.example.esecBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM_gcg5kI4V40oJK_1TxpC5H_UFfLNB4I',
    appId: '1:429164703926:ios:96d7952d75e3cee8fbb617',
    messagingSenderId: '429164703926',
    projectId: 'esec-bus-01',
    storageBucket: 'esec-bus-01.firebasestorage.app',
    iosBundleId: 'com.example.esecBus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuyD5evbkbnqQbvcqXg124aXYucFOwPOw',
    appId: '1:429164703926:web:8144a1c589694de1fbb617',
    messagingSenderId: '429164703926',
    projectId: 'esec-bus-01',
    authDomain: 'esec-bus-01.firebaseapp.com',
    storageBucket: 'esec-bus-01.firebasestorage.app',
  );
}
